title: Royal-Blade Wiki
description: Documentation Source For The Royal Blade Experience.
repository: ZercoreX/Royal-Blade-Wiki-2
permalink: pretty

social:
  game: https://www.roblox.com/games/5236473035
  discord: https://discord.gg/aDqqdwb
  group: https://www.roblox.com/groups/6825668/Royal-Verse
  gameTwitter: https://twitter.com/RoyalVerseGames
  creatorTwitter: https://twitter.com/ZercoreX
